import { DataPlan } from "../types";

export const availableDataPlans: DataPlan[] = [
  {
    id: 'plan_1',
    provider: 'Starhub',
    name: '5GB free every week',
    dataFreeInGb: 5,
    billingCycleInDays: 7,
    price: 7,
    excessChargePerMb: 0.01,
  },
  {
    id: 'plan_2',
    provider: 'Starhub',
    name: '50GB free every month',
    dataFreeInGb: 50,
    billingCycleInDays: 30,
    price: 50,
    excessChargePerMb: 0.01,
  },
  {
    id: 'plan_3',
    provider: 'Singtel',
    name: '1GB free every day',
    dataFreeInGb: 1,
    billingCycleInDays: 1,
    price: 1,
    excessChargePerMb: 0.015,
  },
  {
    id: 'plan_4',
    provider: 'Singtel',
    name: '25GB free every month',
    dataFreeInGb: 25,
    billingCycleInDays: 30,
    price: 28,
    excessChargePerMb: 0.012,
  },
  {
    id: 'plan_5',
    provider: 'M1',
    name: '7GB free every week',
    dataFreeInGb: 7,
    billingCycleInDays: 7,
    price: 10,
    excessChargePerMb: 0.012,
  },
  {
    id: 'plan_6',
    provider: 'Circle Life',
    name: 'Pay as you go',
    dataFreeInGb: 0,
    billingCycleInDays: 30,
    price: 0,
    excessChargePerMb: 0.0015,
  },
];